module.exports = {
  "createdBy": {
    "description": "User who created the resource",
    "model": "user",
    "skipAll": true
  },
  "updatedBy": {
    "description": "Last user who updated the resource",
    "model": "user",
    "skipAll": true
  },
  "createdAt": {
    "type": "datetime",
    "skipAll": true
  },
  "updatedAt": {
    "type": "datetime",
    "skipAll": true
  },
  "invoiceNumber": {
    "description": "Unique invoice idetification number",
    "unique": true,
    "type": "string"
  },
  "status": {
    "type": "string",
    "defaultsTo": "draft",
    "enum": [
      "draft",
      "approved",
      "delivered",
      "partial",
      "paid",
      "cancelled",
      "refunded",
      "due"
    ]
  },
  "host": {
    "model": "company",
    "skipAll": true
  },
  "client": {
    "description": "Client who will receive the invoice",
    "required": true,
    "mustExist": true,
    "model": "company"
  },
  "currency": {
    "required": true,
    "model": "currency"
  },
  "usageReportId": {
    "description": "If the invoice has been generated by the AWS Usage report, should have this id",
    "model": "awsUsageReport",
    "skipAll": true
  },
  "issueDate": {
    "type": "datetime"
  },
  "dueDate": {
    "type": "datetime"
  },
  "products": {
    "description": "Add products to invoice",
    "productList": true,
    "type": "json",
    "defaultsTo": []
  },
  "amount": {
    "type": "float",
    "defaultsTo": 0,
    "skipAll": true
  },
  "tax": {
    "type": "float",
    "defaultsTo": 0,
    "skipAll": true
  },
  "total": {
    "type": "float",
    "defaultsTo": 0,
    "skipAll": true
  },
  "exchangeRate": {
    "type": "float",
    "skipAll": true
  },
  "paymentResponsibles": {
    "description": "Send notifications about this AWS Account payments to these users",
    "type": "array",
    "multiple": "user"
  },
  "template": {
    "description": "Detailed quote proposal.",
    "required": true,
    "type": "string",
    "html": true,
    "target": "template",
    "query": {
      "type": "invoice"
    }
  },
  "specialObservations": {
    "description": "Specify if the invoice has some special observation",
    "type": "string",
    "longtext": true
  },
  "views": {
    "description": "How many views has the invoice",
    "type": "array",
    "defaultsTo": [],
    "skipAll": true
  }
}